### ISSUE TITLE
your tech support has been up for over 24 days! This project died ?

### ISSUE THREAD

**Issue by aituganov1** [cryptonator/merchant-api-sdk-php#2]
your tech support has been up for over 24 days! This project died ?
After 7 days I'm writing a letter to the FSB and the MVD. Let open a criminal case of fraud I had once written to them, the thief found.
I want my 7000$

**Comment by kk999999999** [comment]
ฉันต้องการ 7000 เหรียญของฉัน

**Comment by iafilin** [comment]
Тут не место такое обсуждать, но все же хотелось бы услышать официальный ответ от администрации сайта cryptonator.com по поводу сообщений выше.

**Comment by BIGCRYPTO001** [comment]
I cannot open my wallet waiting 3 week

**Comment by BIGCRYPTO001** [comment]
Hello motherfucker
